workflows:
  qa-workflow---for-ios-tests:
    name: QA workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: qa
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
        - name: Widget tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json

        - name: Integration tests
        script: |
        mkdir -p test-results 
        flutter -d iPhone test --machine > test-results/flutter.json integration_test/mobile_app_test.dart -d iPhone 
        test_report: test-results/flutter.json
        
        - name: Integration tests
        script: |
        - flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk # include APK artifacts
      - build/**/outputs/bundle/**/*.aab # include AAB artifacts
      - build/**/outputs/**/mapping.txt # include mapping file artifacts
      - '*.snap' # include snapshot artifacts
      - build/windows/**/*.msix # include Windows MSIX artifacts
      - flutter_drive.log # include the Flutter Drive log as an artifact
    publishing:
      email:
        recipients:
          - bkaric@pa.tech387.com
